### ISSUE TITLE
Switch to patched version of tree-sitter-clojure

### ISSUE THREAD

**Issue by wenkokke** [cursorless-dev/vscode-parse-tree#23]
The tree-sitter-clojure package uses exact dependencies for nan and tree-sitter-cli, and erroneously—I think—introduces an exact dependency for web-tree-sitter.

We should fork tree-sitter-clojure, loosen these dependencies, test if the resulting parser still works, and if so start using the less restricted version in vscode-parse-tree.

**Comment by pokey** [comment]
All looks good, tho I'd add that we should probably also file a PR against the `tree-sitter-clojure` repo, no?

**Comment by wenkokke** [comment]
It’s already fixed!
