### ISSUE TITLE
[Feature request] Api for loading custom languages

### ISSUE THREAD

**Issue by RedCMD** [cursorless-dev/vscode-parse-tree#34]
Would be nice to be able to load a custom language via your extension without needing to fork it

Just a single function that takes a file path to the `.wasm` file and a language id

Or even a way to select a builtin `.wasm` file while using my own custom `languageId`

**Comment by pokey** [comment]
Interesting idea. So it sounds like you'd like a function in this extension's api that you could call from another extension to register a wasm for a particular language id? Sounds easy enough. I'd be open to a PR
