### ISSUE TITLE
 Upcoming change to tree-sitter-clojure

### ISSUE THREAD

**Issue by sogaiu** [cursorless-dev/vscode-parse-tree#58]
I'm opening this issue to let the maintainers know that we're planning to merge a change to the tree-sitter-clojure master branch that might affect this repository.

The change is here: sogaiu/tree-sitter-clojure#31

A brief overview of the changes follows.

`kwd_lit` and `sym_lit` will now contain up to 3 _new_ nodes:

```
(kwd_lit
  ns: (kwd_ns)
  delimiter: "/"
  name: (kwd_name))

(sym_lit
  ns: (sym_ns)
  delimiter: "/"
  name: (sym_name))
```

Only the `(kwd_name)` and `(sym_name)` are required.

`sym_lit` nodes can still contain metadata nodes (this is unchanged).

---

We looked at the `package.json` and `yarn.lock` files in this repository but didn't quite determine exactly which commit or version was being depended on.  So just in case...

If you are not prepared to use these changes, please consider using the [commit at tag v0.0.9](https://github.com/sogaiu/tree-sitter-clojure/tree/v0.0.9) or the [corresponding tagged release](https://github.com/sogaiu/tree-sitter-clojure/releases/tag/v0.0.9).  (Those should be functionally equivalent to the current master branch ([8c23e0ec07](https://github.com/sogaiu/tree-sitter-clojure/tree/8c23e0ec078af461ccad43fffbbfc204aa6bc238) as of this writing).)

If the changes do cause issues, please tell us.

Our current plan is to merge around 2023-01-05 which is in about 2 weeks time.

---

On a more general note...

Though at this time we don't anticipate many changes going forward, we're planning to post certain change-related announcements to [a pinned issue](https://github.com/sogaiu/tree-sitter-clojure/issues/33) ahead of merging such changes.

__Please have a look at the issue and consider subscribing :)__

**Comment by pokey** [comment]
thanks for the heads up!  we pin all our versions, because most tree-sitter grammar maintainers are not as diligent as you 😄.  See https://github.com/tree-sitter/tree-sitter/discussions/1768 for an interesting relevant discussion if you've not already seen it
