### ISSUE TITLE
xml Tree sitter parser fails on `<?`

### ISSUE THREAD

**Issue by AndreasArvidsson** [cursorless-dev/vscode-parse-tree#74]
File starting with `<?` fails with error:
![image](https://github.com/cursorless-dev/vscode-parse-tree/assets/3511326/27c1964e-4d0b-483f-a9be-7112c7aaacb3)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<root>
</root>
```

There is some weirdness where that even if you comment this line you have to reload the vscode window until the parser starts working again. On the other hand if you load the language without this line and then added it appears to be working, but the range of the first node after `<?...?>` becomes incorrect.

The parser we are using is tested for this so I do wonder if we are doing something incorrectly with our implementation.
https://github.com/ObserverOfTime/tree-sitter-xml/blob/master/tree-sitter-xml/test/corpus/standard.txt

**Comment by pokey** [comment]
Their parser has tests for it, as you mention, but the tests generally don't run on the wasm version, and when I tried their wasm version on its own, I got an error message

**Comment by AndreasArvidsson** [comment]
I guess we should file an issue then?

**Comment by AndreasArvidsson** [comment]
This might be a related issue. The error message looks similar enough
https://github.com/tree-sitter/tree-sitter/issues/2610

**Comment by AndreasArvidsson** [comment]
The problem appears to be that `resolveSymbol("isalnum")` returns undefined. `.apply` is then called on that undefined value

**Comment by ObserverOfTime** [comment]
Can you check if ObserverOfTime/tree-sitter-xml@62f9a95 solves the issue?

**Comment by pokey** [comment]
I can confirm this issue is fixed. Thanks!

**Comment by pokey** [comment]
oh actually didn't realise this issue was on our repo rather than tree-sitter-xml. I'll leave this open here until we bump to the newer tree-sitter-xml

**Comment by pokey** [comment]
this is now released in vscode-parse-tree 0.31.0

**Comment by AndreasArvidsson** [comment]
Tested and working. Finally I can use Cursorless together with maven!
